---
- name: Juniper Full Config Replace
  hosts: juniper
  gather_facts: False
  tasks:
    - napalm_install_config:
        replace_config: True
        commit_changes: False
        config_file: "CFGS/{{ inventory_hostname }}-default.txt"
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
